comp: cls all

up: cls all upload

mon: cls all upload monitor

cls:
	clear
	
## Configuration for Arduino UNO
#BOARD_TAG	= uno
#MONITOR_PORT	= /dev/ttyACM*

# Configuration for Arduino nano
BOARD_TAG   = nano
BOARD_SUB   = atmega328
MONITOR_PORT  = /dev/ttyUSB*

CXXFLAGS_STD = -std=gnu++17

include /usr/share/arduino/Arduino.mk

